BATCH_SIZE = 16
INPUT_HEIGHT = 360
INPUT_WIDTH = 640
OUTPUT_WIDTH = 160
OUTPUT_HEIGHT = 90
OG_DOWNSAMPLE_SIZE = 12
IMAGE_PATH = r'C:\Users\timf3\PycharmProjects\AnacondaTest\Dataset\Train\testset\\'
CONFIG_PATH = r'C:\Users\timf3\PycharmProjects\AnacondaTest\Custom Data txt\Training\bigfileCNN3test.txt'
CHECKPOINT_PATH = '\\'
VID6_PATH = r'C:\Users\timf3\PycharmProjects\AnacondaTest\vid4.avi'
THRESHOLD_VAL = 0.99999